"""Add Google ID and name, make lecture/section nullable

Revision ID: 439ecf10a557
Revises: 657c0270436b
Create Date: 2020-06-15 23:02:30.272006

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '439ecf10a557'
down_revision = '657c0270436b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('course', schema=None) as batch_op:
        batch_op.create_unique_constraint(batch_op.f('uq_course_code'), ['code'])

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('google_id', sa.String(length=256), nullable=False, default=''))
        batch_op.add_column(sa.Column('name', sa.String(length=64), nullable=True))
        batch_op.create_unique_constraint(batch_op.f('uq_user_google_id'), ['google_id'])
        batch_op.create_unique_constraint(batch_op.f('uq_user_username'), ['username'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('uq_user_username'), type_='unique')
        batch_op.drop_constraint(batch_op.f('uq_user_google_id'), type_='unique')
        batch_op.drop_column('name')
        batch_op.drop_column('google_id')

    with op.batch_alter_table('course', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('uq_course_code'), type_='unique')

    # ### end Alembic commands ###
