"""Add Course, CourseUser, User tables

Revision ID: 0f61881252a2
Revises: 
Create Date: 2020-06-09 01:26:36.796220

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0f61881252a2'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('course',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=32), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    op.create_table('course_user',
    sa.Column('user', sa.Integer(), nullable=False),
    sa.Column('course', sa.Integer(), nullable=False),
    sa.Column('user_type', sa.Enum('STUDENT', 'INSTRUCTOR', name='usertype'), nullable=False),
    sa.Column('lecture', sa.String(length=32), nullable=False),
    sa.Column('section', sa.String(length=32), nullable=False),
    sa.Column('dropped', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['course'], ['course.id'], ),
    sa.ForeignKeyConstraint(['user'], ['user.id'], ),
    sa.PrimaryKeyConstraint('user', 'course')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('course_user')
    op.drop_table('user')
    op.drop_table('course')
    # ### end Alembic commands ###
